### ISSUE TITLE
Gallery page

### ISSUE THREAD

**Issue by sunil3590** [codeshaala/codeshaala-dev#4]
Matrix style gallery
Pop up on click
Left - Right buttons

New images added to the gallery folder should be shown in the gallery without code changes

**Comment by rajkamal89** [comment]
Created Portfoilio Section:
Change Content According to your requirement:

https://codeshaala.github.io/codeshaala-dev/portfolio.html

**Comment by anusharish** [comment]
- Redirection from this page to other pages needs to be handled. 
- Gallery option on the top right menu disappears when this page is opened.
- Banner and "Benifits of codeshaala" section should be removed. This page should only contain images.

**Comment by rajkamal89** [comment]
DONE : Redirection from this page to other pages needs to be handled.
DONE : Gallery option on the top right menu disappears when this page is opened.
DONE : Benifits of codeshaala (Removed).

**Comment by rajkamal89** [comment]
Provided you the gallery structure.
Upload images according to your requirement.
